name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MAATEST-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json", "presets", "MaaTest.exe"]'
          exclude_files: '["*model/ocr/**"]'
          mirrorchyan_rid: MaaTest

          owner: Gugugu729
          repo: MaaTest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
